### ISSUE TITLE
On E10s, Marionette Tests for HTTP <location|refresh> header redirections raise IOError

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#727]
On E10s, Marionette Python Client's funciton `marionette.navigate(url)` raises `IOError` after being paused for several minutes. The `url` has to be one which gets blocked by RequestPolicy due to HTTP header redirections.

The exact failure looks as follows:

```
Traceback (most recent call last):
  File "/moz/rp/.venv/local/lib/python2.7/site-packages/marionette/marionette_test.py", line 296, in run
    testMethod()
  File "/moz/rp/tests/marionette/tests/redirections/test_auto_redirect.py", line 71, in test_redirect_notification_appears_or_not
    test_appear("redirect-http-refresh-header.php")
  File "/moz/rp/tests/marionette/tests/redirections/test_auto_redirect.py", line 52, in test_appear
    self._navigate_expecting_r21n(test_url)
  File "/moz/rp/tests/marionette/tests/redirections/test_auto_redirect.py", line 147, in _navigate_expecting_r21n
    self.marionette.navigate(url)
  File "/moz/rp/.venv/local/lib/python2.7/site-packages/marionette_driver/marionette.py", line 1452, in navigate
    self._send_message("get", {"url": url})
  File "/moz/rp/.venv/local/lib/python2.7/site-packages/marionette_driver/decorators.py", line 36, in _
    return func(*args, **kwargs)
  File "/moz/rp/.venv/local/lib/python2.7/site-packages/marionette_driver/marionette.py", line 692, in _send_message
    raise IOError("process died with returncode %s" % returncode)
IOError: process died with returncode None
```

As you can see the test page is `"redirect-http-refresh-header.php"`, but the same happens with `"redirect-http-refresh-header.php"`.

This issue might be related to [Mozilla Bug 1209373](https://bugzilla.mozilla.org/show_bug.cgi?id=1209373) (`marionette.navigate() throws IOError instead of TimeoutException`).

For now I'll disable the failing tests.

**Comment by myrdd** [comment]
I guess this is a bug in Marionette, so I've reported it:
https://bugzilla.mozilla.org/show_bug.cgi?id=1219969
